Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : felipe
// Descrição   : aumento de 25% do salario
// Autor(a)    : arthur
// Data atual  : 03/03/2023
Var
// Seção de Declarações das variáveis 
    sal, aum: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva(" digite o valor do salário atual   ")
   leia( sal)
    aum <- sal * 1.25
    escreva("Seu novo salário é de R$ ",aum)
Fimalgoritmo